version: '3.8'
services:
  api:
    build: .
    ports:
      - '5001:5001'
    environment:
      - MONGO_URI=mongodb://mongo:27017/delivery
      - PORT=5001
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
